/**
 * Design editing pipeline.
 *
 * Takes existing code plus an edit instruction and streams back the modified
 * result as a full rewritten TSX file generated by the model.
 */

import type { EditOpts, StreamEvent } from "./types";
import { streamDesignGeneration } from "./providers";
import { buildFullEditPrompt } from "./prompts";
import {
  buildAssetPlaceholders,
  substituteAssetPlaceholders,
  sanitizeMediaPaths,
} from "./utils/assets";

export async function* editCard(opts: EditOpts): AsyncGenerator<StreamEvent> {
  const {
    code,
    editPrompt,
    selectedComponent,
    style,
    assets,
    model,
    temperature,
    maxTokens,
    abortSignal,
    onFinish,
  } = opts;

  const startTime = Date.now();

  if (!code.trim()) {
    const error = {
      code: "EMPTY_SOURCE",
      message: "Cannot edit empty code. Generate a component first.",
    };
    onFinish?.({ success: false, error, durationMs: Date.now() - startTime });
    yield { type: "error", error };
    return;
  }

  const { promptAssets, assetMap } = buildAssetPlaceholders(assets);
  const { system: systemPrompt, user: userPrompt } = buildFullEditPrompt({
    code,
    editPrompt,
    selectedComponent,
    includeGlass: style === "apple-glass",
    assets: promptAssets,
  });

  const imageContentParts = assets
    ?.filter((asset) => asset.base64Data && asset.mediaType)
    .map((asset) => ({
      base64Data: asset.base64Data!,
      mediaType: asset.mediaType!,
      label: asset.alt ?? `Asset ${asset.id}`,
    }));

  let fullResponse = "";
  let startEventForwarded = false;

  for await (const event of streamDesignGeneration({
    systemPrompt,
    userPrompt,
    imageContentParts: imageContentParts?.length ? imageContentParts : undefined,
    model,
    temperature,
    maxTokens,
    abortSignal,
  })) {
    if (event.type === "start") {
      startEventForwarded = true;
      yield event;
      continue;
    }

    if (event.type === "error") {
      if (!startEventForwarded) {
        yield { type: "start", metadata: { model: model ?? "unknown" } };
      }
      onFinish?.({ success: false, error: event.error, durationMs: Date.now() - startTime });
      yield event;
      return;
    }

    if (event.type === "delta") {
      yield { type: "delta", content: event.content };
      continue;
    }

    if (event.type === "complete") {
      fullResponse = event.content;
    }
  }

  if (!fullResponse.trim()) {
    const error = {
      code: "EMPTY_EDIT_RESPONSE",
      message: "The model returned an empty edit response. Try rephrasing the instruction.",
    };
    onFinish?.({ success: false, error, durationMs: Date.now() - startTime });
    yield { type: "error", error };
    return;
  }

  try {
    const rawCode = stripMarkdownFences(fullResponse);
    const withAssets = assetMap.size > 0 ? substituteAssetPlaceholders(rawCode, assetMap) : rawCode;
    const finalCode = sanitizeMediaPaths(withAssets);

    if (!finalCode.trim()) {
      const error = {
        code: "EMPTY_RESULT",
        message: "Edit produced empty output. Ask the model to retry.",
      };
      onFinish?.({ success: false, error, durationMs: Date.now() - startTime });
      yield { type: "error", error };
      return;
    }

    const metadata = { editMode: "full" };

    onFinish?.({ success: true, content: finalCode, metadata, durationMs: Date.now() - startTime });
    yield {
      type: "complete",
      content: finalCode,
      metadata,
    };
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : "Unknown error applying edit";
    const error = {
      code: "EDIT_FAILED",
      message: `Failed to process edited component: ${message}`,
    };
    onFinish?.({ success: false, error, durationMs: Date.now() - startTime });
    yield { type: "error", error };
  }
}

function stripMarkdownFences(text: string): string {
  const fenceMatch = text.match(/```(?:jsx|tsx|html|typescript)?\n?([\s\S]*?)```/);
  if (fenceMatch) return fenceMatch[1].trim();

  // No fences found — the model may have prepended prose before code.
  // Find the first line that looks like an import/export/comment/"use ... and
  // discard everything before it (prose like "I have the full source...").
  const codeStartPattern = /^(import\s|export\s|\/\/|\/\*|"use |'use )/m;
  const match = text.match(codeStartPattern);
  if (match && match.index != null && match.index > 0) {
    return text.slice(match.index).trim();
  }

  return text.trim();
}
